name: CD

on:
    push:
        branches:
        - main
env:
    DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKERHUB_KEY: ${{ secrets.DOCKER_KEY }}
    IMAGE_NAME: nodejs-app-argocd

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ env.DOCKERHUB_USERNAME }}
            password: ${{ env.DOCKERHUB_KEY }}

        - name: Build Docker image
          run: |
            SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
            docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${SHORT_SHA} .

        - name: Push Docker image
          run: |
            SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
            docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${SHORT_SHA}

        - name: Update values.yaml
          run: |
            cd nodeapp
            SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
            sed -i 's|APP_VERSION:.*|APP_VERSION: '${SHORT_SHA}'|' values.yaml 
            git config --global user.name 'nurawiguna'
            git config --global user.email 'nuraaws11@gmail.com'
            git add values.yaml
            git commit -m "Update values.yaml with the new image tag - ${SHORT_SHA}"
            git push