name: CD

on:
    push:
        branches:
        - main
env:
    DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKERHUB_KEY: ${{ secrets.DOCKER_KEY }}
    IMAGE_NAME: nodejs-app-argocd
    IMAGE_TAG: $(echo ${{ github.sha }} | cut -c1-7)

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ env.DOCKERHUB_USERNAME }}
            password: ${{ env.DOCKERHUB_KEY }}

        - name: Build Docker image
          run: docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

        - name: Push Docker image
          run: docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} 

        - name: Update values.yaml
          run: |
            cd nodeapp
            sed -i 's|APP_VERSION:.*|APP_VERSION: '${{ env.IMAGE_TAG }} '|' values.yaml 
            git config --global user.name 'nurawiguna'
            git config --global user.email 'nuraaws11@gmail.com'
            git add values.yaml
            git commit -m "Update values.yaml with the new image tag - ${{ env.IMAGE_TAG }}"
            git push
